version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - NGINX_IMAGE_URI=$AWS_ACCOUNT_ID.dkr.ecr.ap-northeast-1.amazonaws.com/$NGINX_REPO_NAME
      - RAILS_IMAGE_URI=$AWS_ACCOUNT_ID.dkr.ecr.ap-northeast-1.amazonaws.com/$RAILS_REPO_NAME
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $NGINX_IMAGE_URI:$latest .
      - docker tag $NGINX_REPO_NAME:latest $NGINX_IMAGE_URI:$IMAGE_TAG
      - docker build -t $RAILS_IMAGE_URI:$latest .
      - docker tag $RAILS_REPO_NAME:latest $RAILS_IMAGE_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $NGINX_IMAGE_URI:$IMAGE_TAG
      - docker push $RAILS_IMAGE_URI:$IMAGE_TAG
      - printf '[{"name":"nginx","imageUri":"%s"}]' $NGINX_IMAGE_URI > imagedefinitions.json
      - printf '[{"name":"rails","imageUri":"%s"}]' $RAILS_IMAGE_URI > imagedefinitions.json
artifacts:
  files:
      - imagedefinitions.json 
