version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - NGINX_IMAGE_URI=$AWS_ACCOUNT_ID.dkr.ecr.ap-northeast-1.amazonaws.com/$NGINX_REPO_NAME
      - RAILS_IMAGE_URI=$AWS_ACCOUNT_ID.dkr.ecr.ap-northeast-1.amazonaws.com/$RAILS_REPO_NAME
      - IMAGE_TAG=$CODEBUILD_RESOLVED_SOURCE_VERSION
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build --no-cache -t $NGINX_IMAGE_URI:$IMAGE_TAG .
      - docker build --no-cache -t $RAILS_IMAGE_URI:$IMAGE_TAG .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $NGINX_IMAGE_URI:$IMAGE_TAG
      - docker push $RAILS_IMAGE_URI:$IMAGE_TAG
      - cat taskdef-production.json | sed -e s@\<NGINX_IMAGE_NAME\>@$NGINX_IMAGE_URI:$IMAGE_TAG@ -e s@\<RAILS_IMAGE_NAME\>@$RAILS_IMAGE_URI:$IMAGE_TAG@ > imagedefinitions.json
artifacts:
  files:
      - appspec.yml
      - imagedefinitions.json 
