version: "3"
services:
  db:
    image: mysql:5.7
    env_file:
      - ./environments/db.env
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"

  app:
    build:
      context: .
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec puma -C config/puma.rb"
    volumes:
      - .:/opt/myapp
      - public-data:/opt/myapp/public
      - tmp-data:/opt/myapp/tmp
      - log-data:/opt/myapp/log
    depends_on:
      - db
    tty: true
    stdin_open: true
    
  web:
    build:
      context: containers/nginx
    volumes:
      - public-data:/opt/myapp/public
      - tmp-data:/opt/myapp/tmp
    ports:
      - "80:80"
    depends_on:
      - app
volumes:
  public-data:
  tmp-data:
  log-data:
  db-data: